#!/bin/sh
export IMG=build/ch.elf
exec openocd -f interface/stlink-v2.cfg -f target/stm32f4x_stlink.cfg -c "init" -c "reset init" -c "halt" -c "flash write_image erase $IMG" -c "verify_image $IMG" -c "reset run" -c shutdown 
